/**
 * layout.jsx
 */

import { SiteHeader } from "@/components/navigation/site-header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/footer";
import CatchTheOffer from "@/components/footer/catch-the-offer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SiteHeader />
        {children}
        <CatchTheOffer />
        <Footer />
      </body>
    </html>
  );
}
